import Gamepad from "./assets/items/Gamepad.svg";
import Keyboard from "./assets/items/Keyboard.svg";
import GamingMonitor from "./assets/items/GamingMonitor.svg";
import Chair from "./assets/items/Chair.svg";
import NorthCoat from "./assets/items/northcoat.svg";
import GucciBag from "./assets/items/GucciBag.svg";
import RGB from "./assets/items/RGB.svg";
import SmallBookSelf from "./assets/items/SmallBookSelf.svg";
import DogFood from "./assets/items/DogFood.svg";
import CanonCamera from "./assets/items/CanonCamera.svg";
import ASUSLaptop from "./assets/items/ASUSLaptop.svg";
import CurologyProductSet from "./assets/items/CurologyProductSet.svg";
import KidsElectricCar from "./assets/items/KidsElectricCar.svg";
import SoccerCleats from "./assets/items/SoccerCleats.svg";
import USBGamepad from "./assets/items/USBGamepad.svg";
import QuiltedSatinJacket from "./assets/items/QuiltedSatinJacket.svg";
import IPhone from "./assets/IPhone.svg";
import PlayStation from "./assets/ps5-slim.svg";
import Speakers from "./assets/Speakers.svg";
import Perfume from "./assets/Perfume.svg";
import JBLBOOMBOX from "./assets/JBL_BOOMBOX.svg";
import Oneestar from "./assets/stars/OneStar.svg";
import TowStar from "./assets/stars/TowStar.svg";
import ThreeStar from "./assets/stars/ThreeStar.svg";
import FourStar from "./assets/stars/FourStar.svg";
import FourHalfStar from "./assets/stars/FourHalfStar.svg";
import Fivestar from "./assets/stars/Fivestar.svg";

export const productsData = [
  {
    id: 1,
    title: "HAVIT HV-G92 Gamepad",
    image: Gamepad,
    discount: "-40%",
    price: 120,
    oldPrice: 150,
    ratingImage: Fivestar,
    reviews: 88,
    category: "Flash Sales",
    categoryType: "Electronics",
  },
  {
    id: 2,
    title: "AK-900 Wired Keyboard",
    image: Keyboard,
    discount: "-35%",
    price: 960,
    oldPrice: 1160,
    ratingImage: FourStar,
    reviews: 75,
    category: "Flash Sales",
    categoryType: "Electronics",
  },
  {
    id: 3,
    title: "IPS LCD Gaming Monitor",
    image: GamingMonitor,
    discount: "-30%",
    price: 370,
    oldPrice: 400,
    ratingImage: Fivestar,
    reviews: 99,
    category: "Flash Sales",
    categoryType: "Electronics",
  },
  {
    id: 4,
    title: "S-Series Comfort Chair",
    image: Chair,
    discount: "-25%",
    price: 375,
    oldPrice: 400,
    ratingImage: FourHalfStar,
    reviews: 99,
    category: "Flash Sales",
    categoryType: "Home & Lifestyle",
  },
  {
    id: 5,
    title: "The north coat",
    image: NorthCoat,
    discount: "",
    price: 260,
    oldPrice: 360,
    ratingImage: Fivestar,
    reviews: 65,
    category: "Best Selling Products",
    categoryType: "Women’s Fashion",
  },
  {
    id: 6,
    title: "Gucci duffle bag",
    image: GucciBag,
    discount: "",
    price: 960,
    oldPrice: 1160,
    ratingImage: FourHalfStar,
    reviews: 65,
    category: "Best Selling Products",
    categoryType: "Women’s Fashion",
  },
  {
    id: 7,
    title: "RGB liquid CPU Cooler",
    image: RGB,
    discount: "",
    price: 160,
    oldPrice: 170,
    ratingImage: FourHalfStar,
    reviews: 65,
    category: "Explore Our Products",
    categoryType: "Electronics",
  },
  {
    id: 8,
    title: "Small BookSelf",
    image: SmallBookSelf,
    discount: "",
    price: 360,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 65,
    category: "Explore Our Products",
    categoryType: "Home & Lifestyle",
  },
  {
    id: 9,
    title: "Breed Dry Dog Food",
    image: DogFood,
    discount: "",
    price: 100,
    oldPrice: 0,
    ratingImage: FourStar,
    reviews: 35,
    category: "Explore Our Products",
    categoryType: "Groceries & Pets",
  },
  {
    id: 10,
    title: "CANON EOS DSLR Camera",
    image: CanonCamera,
    discount: "",
    price: 360,
    oldPrice: 0,
    ratingImage: FourStar,
    reviews: 95,
    category: "Best Selling Products",
    categoryType: "Electronics",
  },
  {
    id: 11,
    title: "ASUS FHD Gaming Laptop",
    image: ASUSLaptop,
    discount: "",
    price: 700,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 325,
    category: "Best Selling Products",
    categoryType: "Electronics",
  },
  {
    id: 12,
    title: "Curology Product Set",
    image: CurologyProductSet,
    discount: "",
    price: 500,
    oldPrice: 0,
    ratingImage: FourStar,
    reviews: 145,
    category: "Explore Our Products",
    categoryType: "Health & Beauty",
  },
  {
    id: 13,
    title: "Kids Electric Car",
    image: KidsElectricCar,
    discount: "",
    price: 960,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 65,
    category: "Explore Our Products",
    categoryType: "Baby & Toys",
  },
  {
    id: 14,
    title: "Jr. Zoom Soccer Cleats",
    image: SoccerCleats,
    discount: "",
    price: 1160,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 35,
    category: "Best Selling Products",
    categoryType: "Sports & Outdoors",
  },
  {
    id: 15,
    title: "GP11 Shooter USB Gamepad",
    image: USBGamepad,
    discount: "",
    price: 660,
    oldPrice: 0,
    ratingImage: FourHalfStar,
    reviews: 55,
    category: "Explore Our Products",
    categoryType: "Electronics",
  },
  {
    id: 16,
    title: "Quilted Satin Jacket",
    image: QuiltedSatinJacket,
    discount: "",
    price: 660,
    oldPrice: 0,
    ratingImage: FourHalfStar,
    reviews: 55,
    category: "Best Selling Products",
    categoryType: "Men’s Fashion",
  },
  {
    id: 17,
    title: "IPhone 13 Pro Max",
    image: IPhone,
    discount: "",
    price: 1200,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 25,
    category: "Best Selling Products",
    categoryType: "Electronics",
  },
  {
    id: 18,
    title: "PlayStation 5",
    image: PlayStation,
    discount: "",
    price: 1400,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 40,
    category: "Best Selling Products",
    categoryType: "Electronics",
  },
  {
    id: 19,
    title: "Speakers",
    image: Speakers,
    discount: "",
    price: 800,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 90,
    category: "Best Selling Products",
    categoryType: "Electronics",
  },
  {
    id: 20,
    title: "Perfume",
    image: Perfume,
    discount: "",
    price: 300,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 120,
    category: "Best Selling Products",
    categoryType: "Home & Lifestyle",
  },
  {
    id: 21,
    title: "JBL BOOMBOX",
    image: JBLBOOMBOX,
    discount: "",
    price: 450,
    oldPrice: 0,
    ratingImage: Fivestar,
    reviews: 160,
    category: "Best Selling Products",
    categoryType: "Electronics",
  },
];
